apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-mgmt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: emp-mgmt
  template:
    metadata:
      labels:
        app: emp-mgmt
    spec:
      containers:
      - name: emp-mgmt
        image: "h4ck3rd33p/employee-management-flask-app"
        ports:
        - containerPort: 10000
        env:
        - name: NAME
          value: "World"
        - name: DATABASE_URL
          value: "sqlite:////app/instance/employee.db"
---
apiVersion: v1
kind: Service
metadata:
  name: emp-mgmt
spec:
  type: NodePort
  selector:
    app: emp-mgmt
  ports:
  - port: 10000
    targetPort: 10000
    nodePort: 31000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emp-mgmt-ingress
spec:
  rules:
  - host: employeelovescode.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: emp-mgmt
            port:
              number: 10000
